name: education_planner
description: A module for Artemis that manages education goals and weekly activity plans
version: 0.1.0
homepage: https://github.com/rummel-tech/education-planner

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
